### ISSUE TITLE
Support for Boards with Arduino Bootloader

### ISSUE THREAD

**Issue by syberphunk** [eried/Arduino#8]
Hello,

At the Leeds Hackspace one of our members has altered the minimus32 to work as an Arduino Leonardo. He has uploaded the hardware profile/template/config files to be able to compile to it here:

https://github.com/pbrook/minimus-arduino

Is it possible to have this incorporated into the installer in some way and/or support for pulling in hardware profiles such as this? The small board is rather popular because it is cheaper than an Arduino but has just as much functionality (it uses the Atmega32u iirc).

Thanks!

**Comment by eried** [comment]
Sure I can add the board. Will be nice anyway to get it added to the official arduino too.

**Comment by syberphunk** [comment]
Also I'm not sure if the Arduino IDE has (finally) updated its avr-gcc, but it didn't (in 1.0.1 at least) support the ATMega32u, so that may need to be incorporated? (ie: http://andybrown.me.uk/wk/2012/04/28/avr-gcc-4-7-0-and-avr-libc-1-8-0-compiled-for-windows/) I think that's about it.

I basically thought your work would be better to embellish upon than my lazy effort of combining parts together (http://www.stanto.com/arduino/arduino-ide-on-windows/)

Thanks!
